development:
  adapter: postgresql
  encoding: unicode
  database: children_development
  pool: 5
  username: rails
  password: rails

test:
  adapter: postgresql
  encoding: unicode
  database: children_test
  pool: 5
  username: rails
  password: rails

production:
  adapter: postgresql
  encoding: unicode
  database: children_production
  pool: 5
  username: rails
  password: rails
